### ISSUE TITLE
Refactoring to tiny functions

### ISSUE THREAD

**Issue by TehShrike** [toish/chromatism#11]
Goal: expose a bunch of tiny operation functions that people can bundle into their webapps without unnecessary byte-size-guilt

Work is happening in the [refactor](https://github.com/toish/chromatism/tree/refactor) branch.

- [x] disconnect all the operation functions from each other so that each file can be accessed directly ([#9](https://github.com/toish/chromatism/pull/9))
- [x] make a basic test for each operation based on the current behavior (#13)
- [x] split all helpers out into their own modules (#14)
- [x] change CJS to ESM (#18, #20)
- [x] eliminate or make more efficient the search for a conversion path in convert-to-type.js

Longer shots that can wait for another version:

- disconnect the conversion functions from each other and change operations to all return a single format, like XYZ
- expose XYZ-to-whatever conversion functions that people can pull in individually as they need

**Comment by toish** [comment]
@TehShrike Will be working on this! Currently in the UK at the moment with intermittent internet :(

**Comment by TehShrike** [comment]
I have pull requests open for the tests and splitting the helpers out.  Once those are merged, I'll make the switch to ESM and we can bikeshed the best conversion path solution.

**Comment by toish** [comment]
@TehShrike Merged! Thanks again for all of this! Sorry I've been so absent, holiday's getting in the way.

**Comment by TehShrike** [comment]
Once #20 is merged we just have to decide what to do with convert-to-type.js.  We can chat about that in Discord

**Comment by toish** [comment]
Merged #20! Also fixed HSV=>RGB inefficiency in #25!
